# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Blog1729
tagline:          Notes and things
url:              http://blog1729.github.io
paginate:         1
baseurl:          /
author:
  name:           Blog1729
  url:            http://blog1729.github.io
  email:          nil

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/blog1729/blog1729.github.io
