# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Blog1729
tagline:             Notes and stuff
description:         $\int_{\partial\Omega} \omega  = \int_{\Omega} \mathrm{d}\omega$
url:                 http://blog1729.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Blog1729
  url:               http://blog1729.github.io
  email:             

# Custom vars
version:             1.0.0
